export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';

export const USER_PUBLIC_INFO_REQUEST = 'USER_PUBLIC_INFO_REQUEST';
export const USER_PUBLIC_INFO_SUCCESS = 'USER_PUBLIC_INFO_SUCCESS';
export const USER_PUBLIC_INFO_ERROR = 'USER_PUBLIC_INFO_ERROR';

export const USER_CONTACT_REQUEST = 'USER_CONTACT_REQUEST';
export const USER_CONTACT_SUCCESS = 'USER_CONTACT_SUCCESS';
export const USER_CONTACT_ERROR = 'USER_CONTACT_ERROR';

export const USER_SET_IMPERSONATED = 'USER_SET_IMPERSONATED';
export const USER_CLEAR_IMPERSONATED = 'USER_CLEAR_IMPERSONATED';

export const USER_ALREADY_LOADED = 'USER_ALREADY_LOADED';
