export const NOTIFICATION_CREATE = 'NOTIFICATION_CREATE';
export const NOTIFICATION_DEQUEUE = 'NOTIFICATION_DEQUEUE';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';
export const NOTIFICATION_HANDLE_BUTTON = 'NOTIFICATION_HANDLE_BUTTON';
export const NOTIFICATION_CLEAR_ALL = 'NOTIFICATION_CLEAR_ALL';
