export const COLLECTIONS_FETCH_REQUEST = 'COLLECTIONS_FETCH_REQUEST';
export const COLLECTIONS_FETCH_SUCCESS = 'COLLECTIONS_FETCH_SUCCESS';
export const COLLECTIONS_FETCH_ERROR = 'COLLECTIONS_FETCH_ERROR';

export const COLLECTIONS_SINGLE_COLLECTION_FETCH_REQUEST = 'COLLECTIONS_SINGLE_COLLECTION_FETCH_REQUEST';
export const COLLECTIONS_SINGLE_COLLECTION_FETCH_SUCCESS = 'COLLECTIONS_SINGLE_COLLECTION_FETCH_SUCCESS';
export const COLLECTIONS_SINGLE_COLLECTION_FETCH_ERROR = 'COLLECTIONS_SINGLE_COLLECTION_FETCH_ERROR';
export const COLLECTIONS_LOAD_MORE = 'COLLECTIONS_LOAD_MORE';

export const COLLECTIONS_FETCH_ARTWORKS = 'COLLECTIONS_FETCH_ARTWORKS';
export const COLLECTIONS_FETCH_ARTWORKS_SUCCESS = 'COLLECTIONS_FETCH_ARTWORKS_SUCCESS';

export const TYPE = 'TYPE';
