export const FILES_ADD = 'FILES_ADD';
export const FILES_REMOVE = 'FILES_REMOVE';
export const FILES_CLEAR_ALL = 'FILES_CLEAR_ALL';

export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';
