export const FEED_ITEMS_FETCH_REQUEST = 'FEED_ITEMS_FETCH_REQUEST';
export const FEED_ITEMS_FETCH_SUCCESS = 'FEED_ITEMS_FETCH_SUCCESS';
export const FEED_ITEMS_FETCH_ERROR = 'FEED_ITEMS_FETCH_ERROR';

export const FEED_DISCOVER_ARTWORKS_FETCH_REQUEST = 'FEED_DISCOVER_ARTWORKS_FETCH_REQUEST';
export const FEED_DISCOVER_ARTWORKS_FETCH_SUCCESS = 'FEED_DISCOVER_ARTWORKS_FETCH_SUCCESS';
export const FEED_DISCOVER_ARTWORKS_FETCH_ERROR = 'FEED_DISCOVER_ARTWORKS_FETCH_ERROR';
