export const ARTWORKS_FETCH_REQUEST = 'ARTWORKS_FETCH_REQUEST';
export const ARTWORKS_FETCH_SUCCESS = 'ARTWORKS_FETCH_SUCCESS';
export const ARTWORKS_FETCH_ERROR = 'ARTWORKS_FETCH_ERROR';

export const ARTWORKS_SINGLE_ARTWORK_FETCH_REQUEST = 'ARTWORKS_SINGLE_ARTWORK_FETCH_REQUEST';
export const ARTWORKS_SINGLE_ARTWORK_FETCH_SUCCESS = 'ARTWORKS_SINGLE_ARTWORK_FETCH_SUCCESS';
export const ARTWORKS_SINGLE_ARTWORK_FETCH_ERROR = 'ARTWORKS_SINGLE_ARTWORK_FETCH_ERROR';

export const ARTWORKS_CLEAR_ALL = 'ARTWORKS_CLEAR_ALL';

export const ARTWORKS_UPLOAD_REQUEST = 'ARTWORKS_UPLOAD_REQUEST';
export const ARTWORKS_UPLOAD_SUCCESS = 'ARTWORKS_UPLOAD_SUCCESS';
export const ARTWORKS_UPLOAD_ERROR = 'ARTWORKS_UPLOAD_ERROR';

export const ARTWORKS_SET_SELECTED = 'ARTWORKS_SET_SELECTED';

export const ARTWORKS_EDIT_SELECTED = 'ARTWORKS_EDIT_SELECTED';

export const ARTWORKS_COMMIT_REQUEST = 'ARTWORKS_COMMIT_REQUEST';
export const ARTWORKS_COMMIT_SUCCESS = 'ARTWORKS_COMMIT_SUCCESS';
export const ARTWORKS_COMMIT_ERROR = 'ARTWORKS_COMMIT_ERROR';

export const ARTWORKS_CHANGE_MODE = 'ARTWORKS_CHANGE_MODE';

export const ARTWORKS_IMAGES_UPLOAD_REQUEST = 'ARTWORKS_IMAGES_UPLOAD_REQUEST';
export const ARTWORKS_IMAGES_UPLOAD_SUCCESS = 'ARTWORKS_IMAGES_UPLOAD_SUCCESS';
export const ARTWORKS_IMAGES_UPLOAD_ERROR = 'ARTWORKS_IMAGES_UPLOAD_ERROR';

export const ARTWORKS_DELETE_REQUEST = 'ARTWORKS_DELETE_REQUEST';
export const ARTWORKS_DELETE_SUCCESS = 'ARTWORKS_DELETE_SUCCESS';
export const ARTWORKS_DELETE_ERROR = 'ARTWORKS_DELETE_ERROR';

export const ARTWORKS_EDIT_FILTER = 'ARTWORKS_EDIT_FILTER';
export const ARTWORKS_RESET_FILTER = 'ARTWORKS_RESET_FILTER';
export const ARTWORKS_APPLY_FILTER_REQUEST = 'ARTWORKS_APPLY_FILTER_REQUEST';
export const ARTWORKS_APPLY_FILTER_SAVE = 'ARTWORKS_APPLY_FILTER_SAVE';
export const ARTWORKS_APPLY_FILTER_SUCCESS = 'ARTWORKS_APPLY_FILTER_SUCCESS';
export const ARTWORKS_APPLY_FILTER_ERROR = 'ARTWORKS_APPLY_FILTER_ERROR';
export const ARTWORKS_CHANGE_SORTING = 'ARTWORKS_CHANGE_SORTING';
export const ARTWORKS_CHANGE_SORTING_SUCCESS = 'ARTWORKS_CHANGE_SORTING_SUCCESS';
export const ARTWORKS_CHANGE_SORTING_ERROR = 'ARTWORKS_CHANGE_SORTING_ERROR';

export const ARTWORKS_CHECK_IMAGES_AVAILABILITY = 'ARTWORKS_CHECK_IMAGES_AVAILABILITY';
export const ARTWORKS_CHECK_IMAGES_AVAILABILITY_SUCCESS = 'ARTWORKS_CHECK_IMAGES_AVAILABILITY_SUCCESS';
export const ARTWORKS_CHECK_IMAGES_AVAILABILITY_ERROR = 'ARTWORKS_CHECK_IMAGES_AVAILABILITY_ERROR';

export const ARTWORKS_POLL_UPDATES_START = 'ARTWORKS_POLL_UPDATES_START';
export const ARTWORKS_POLL_UPDATES_STOP = 'ARTWORKS_POLL_UPDATES_STOP';

export const ARTWORKS_PUBLIC_PROFILE_REQUEST = 'ARTWORKS_PUBLIC_PROFILE_REQUEST';
export const ARTWORKS_PUBLIC_PROFILE_SUCCESS = 'ARTWORKS_PUBLIC_PROFILE_SUCCESS';
export const ARTWORKS_PUBLIC_PROFILE_ERROR = 'ARTWORKS_PUBLIC_PROFILE_ERROR';

export const ARTWORKS_CSV_PARSED = 'ARTWORKS_CSV_PARSED';
export const ARTWORKS_UPDATE_CSV_RECORD = 'ARTWORKS_UPDATE_CSV_RECORD';

export const ARTWORKS_EXPORT_CSV_ERRED = 'ARTWORKS_EXPORT_CSV_ERRED';

export const ARTWORKS_BULK_ACTIONS_REQUEST = 'ARTWORKS_BULK_ACTIONS_REQUEST';
export const ARTWORKS_BULK_ACTIONS_SUCCESS = 'ARTWORKS_BULK_ACTIONS_SUCCESS';
export const ARTWORKS_BULK_ACTIONS_ERROR = 'ARTWORKS_BULK_ACTIONS_ERROR';

export const ARTWORKS_CLICK_TO_VIEW_METADATA = 'ARTWORKS_CLICK_TO_VIEW_METADATA';
export const UPLOAD_VIA = 'UPLOAD_VIA';
export const DELETE_MULTIPLE_ARTWORKS = 'DELETE_MULTIPLE_ARTWORKS';
